version: '3.5'

services:
  redis-cluster:
    image: grokzen/redis-cluster:latest
    environment:
      - IP=${REDIS_CLUSTER_IP}
    expose:
      - 7000
      - 7001
      - 7002
      - 7003
      - 7004
      - 7005
